pipeline {
  agent any
  tools { 
     Allure 'allure'// Jenkins > Global Tool Config: Allure named "allure"
    }
    options {
    timeout(time: 20, unit: 'MINUTES') // To prevent running for long time
  }
  // Binds TEST_CREDS_USR and TEST_CREDS_PSW
  environment { TEST_CREDS = credentials('e2e-test-user') }
  // -eu: shell safety setting (e -Exit immediately if any command fails; u- Treat unset variables as errors.)
  stages {
    stage('Build') {
      nodejs('node22') {
          sh '''
            set -eu
            node -v
            npm -v
            npm ci
            npx playwright install
          '''
        }
    }
    stage('Test') {
      steps {
        nodejs('node22') {
          sh '''
            set -eu
            export TEST_USER_NAME="$TEST_CREDS_USR"
            export TEST_PASSWORD="$TEST_CREDS_PSW"
            npm run test:make-apt
          '''
        }
      }
      post {
        always {
         // Publish Allure results generated by the test run
          allure includeProperties: false,
                 jdk: '',
                 results: [[path: 'allure-results']],
                 reportBuildPolicy: 'ALWAYS'
        }
      }
    }
  }
}